### ISSUE TITLE
Handling custom components lifecycle events (connect, disconnect)

### ISSUE THREAD

**Issue by rubixibuc** [hybridsjs/hybrids#101]
I realize that hybrids supports **connect and disconnect event callbacks attached to properties**, but is there any support for general lifecycle (connectedCallback, disconnectedCallback, and etc...) handling? 

Is there a way to listen for one of those event, **but not create an empty property for it**? 

If there is a reason for not supporting that, is there a pattern for connectedCallback and disconnectedCallback handling with properties **that don't have inherent values**?

Sorry if I'm missing something

**Comment by smalluban** [comment]
> If there is a reason for not supporting that, is there a pattern for connectedCallback and disconnectedCallback handling with properties that don't have inherent values?

Both callbacks are supported, but as you wrote only in the property scope. It is intended behavior, as the whole idea behind the project is to create separate definitions of properties, which can be easily re-used in other components. The global lifecycle leads creating not separated code of the business logic.

I know, that at first, it might be strange, or you may think that eventually, you will need those global lifecycles. However, if you need to do something when the component connects, it usually means that you have to store result of that action inside of the components state. There you have your property, which is tight with the callback. Finally, If you define a property with only `connect` method, `get` and `set` method is set as default, so you can safely use it in your connect callback. 

It would be great if you could show an example with use case, where you think you need those global lifecycles. From my experience with those concepts, we really fast can get into the trap, where we want to apply patterns known from other libraries. Sometimes using hybrids requires looking at the problem from a different perspective.

**Comment by rubixibuc** [comment]
I agree it's a good pattern! I wanted to make sure it was intended to be that way. I thought I was possibly missing something from the documentation

ty!

**Comment by smalluban** [comment]
Feel free to re-open if you have any other questions related to lifecycle events.

**Comment by yohcop** [comment]
Hi, I have a question related to lifecycle events.
How would you focus a textarea when it is created?

```js
const renderEditor = () => {
    return html`<textarea></textarea>`;
}

const connectToTextarea = (host) => {
    const editor = host.render(host).querySelector('textarea');  // host.render(host)...
    editor.focus();
}

define('foo-editor', {
    editor: property(undefined, connectToTextarea),
    render: renderEditor,
});
```

It seems to work... But looks a bit strange / surprising to me. First, I don't want to expose editor as a property really (although I guess it's not here, the property will just always be undefined). And second, it doesn't match the documentation at https://hybrids.js.org/#/core-features/render?id=reference-internals.

I also tried this (without the `property` function), but the `connectToTextarea` doesn't seem to run at all (separately, I can't get it to type-check in typescript).

```js
const connectToTextarea = ({render}) => {
    const editor = render().querySelector('textarea') as HTMLTextAreaElement;
    editor.focus();
    return editor;
}

define('block-editor', {
    editor: connectToTextarea,
    render: renderEditor,
});
```

Other slight variations also didn't work.

Sorry if I'm missing something

**Comment by smalluban** [comment]
The second code example does not work, because you defined it as a function, so it is translated to `{ get: connectToTextarea }`, which provides a getter for the property, and by the design, the property is called only when used somewhere ;)

In hybrids, there are no global lifecycles. Each property must define its own callbacks. As it sometimes can be hard to implement at first (as it is so different from other common solutions), in the end, it's usually much better than you might think.

In your case, try to think first what is a feature that you want to add to your component. It is the ability to focus on the internal textarea. Instead of doing it once (in some global lifecycle), you can make it a useful feature, that can be turned on or off. Here you have a simple implementation of the idea:

```typescript
import { define, html } from "hybrids";

interface BlockEditor {
  autofocus: boolean;
}

export default define<BlockEditor>({
  tag: "block-editor",
  autofocus: property(false, null, function observe(host, value, lastValue) {
    if (value) {
      const el = host.render().querySelector("textarea") as HTMLTextAreaElement;
      el.focus();
    }
  }),
  render: () => html`
    <textarea></textarea>
  `,
});
```

Then in a document or template, you can initialize your element like this:

```html
<block-editor autofocus></block-editor>
```

If you want to make it default, you need to reverse the property (but I think it is more useful to default to false, as it is more complaint with the default behavior of the built-in form elements).

**Comment by yohcop** [comment]
Thanks a lot. Ok, so that's roughly what I had in my first piece of code there. In my case it makes more sense to not offer this API for that specific component, I just want to do it once, as the component is created on user interaction. but that's another question :).

So just to clarify the API, for myself, what is the type of the first argument (`host`) of `connect` (or `observe`) ? The documentation says a host instance, but to take your example with the interface BlockEditor, it is missing a `render` attribute/function. There is of course a `render` on the descriptors passed to define, but that one takes a host as first argument to get descriptor values for rendering. I hope I make sense ;)

The above code, slightly modified to use connect and renamed property for an interesting reason.... turns out, autofocus is already defined on HTMLElement ;)

```js
type BlockEditor = HTMLElement & {
    _unused: number;
}

define<BlockEditor>('block-editor', {
    _unused: property(1, (host: BlockEditor, value) => {
        const el = host.render().querySelector("textarea") as HTMLTextAreaElement;
        //              ^--- Property 'render' does not exist on type 'BlockEditor'. ts(2339)
        el.focus();
    }, undefined),
    render: () => html`
      <textarea></textarea>
    `,
});
```

That being said, it works, just typescript's typechecker complaining.

Thank you!

**Comment by smalluban** [comment]
I forgot about render in the interface, you are right. For simplicity, if you don't call the `render` property from the host, it might be skipped in the interface. Also, the interface does not have to extend `HTMLElement` if you don't use element API directly in side effects functions (where you have to pass the type of the argument). In other cases, the type creates a union with `HTMLElement` interface. This is also a reason why you cannot define properties, which are already in the prototype. I thought that `autofocus` is only on inputs.

Here you have a fully working example: https://codesandbox.io/s/amazing-sun-5gv5z?file=/src/index.ts. I still think that it might be better to provide access to the textarea, rather than creating an empty property.
