### ISSUE TITLE
Observe descriptor cleanup method

### ISSUE THREAD

**Issue by rubixibuc** [hybridsjs/hybrids#103]
Would it make sense for the **observe descriptor handler** to return a **cleanup callback**, similar to the connect descriptor and how effect hooks work in React.

I'm not suggesting this because React does it, but because I see practical use for it.

If I want to perform some action every time a prop changes, and that action requires undoing the previous to start fresh again.

The observe _cleanup_ callback would be executed after a value changes, but before the observe callback is executed

```
observe: (host, value) => {
    api.subscribe(value);

    return () => {
        api.unsubscribe(value)
    }
}
```

**Comment by smalluban** [comment]
I understand your need, but I think you can achieve that in a different way. 

First of all, the `observe` API is for executing a side-effect of the current value of the property. That's why this is called each time when the value changes. Adding cleanup callback may introduce nontrivial cases. You wrote: "action requires undoing the previous to start fresh again" - so in your code example the cleanup should be called when the value changes. However, I think it should be also called when the component is disconnected from the DOM - as in your example you are subscribing value, which must be unsubscribed. In that case, we have a conflict - the value may not change, but we have to call cleanup what so ever... 

The library has an API for that kind of behavior - it is a `connect` method (with returned `disconnect` callback). You can look at the example of how to connect the redux store to web components built with hybrids [here](https://stackblitz.com/edit/hybrids-redux-counter?file=redux-counter.js). The direction of the connection is opposite to your example (the external library controls the value, not the value controls external library), but this is more often use case.

So, what you can do in your case? You can still use the `observe` method, as it also supports the third argument with the `lastValue`. I am sure that your code example is a simplification of real usage, but if it works like you wrote it, you can define your `observe` method just like that:

```javascript
{
  observe: (host, value, lastValue) => {
    if (lastValue !== undefined) {
      api.unsubscribe(lastValue);
     }
     api.subscribe(value);
   },
}
```

Another option is to adopt the `set` method. If the value is controlled by the cache (and you don't need `property` factory features, like fallback support for attributes) you can write your property descriptor like this:

```javascript
{
  set: (host, value, lastValue) => {
     api.unsubscribe(lastValue);
     api.subscribe(value);
     return value;
  },
}
```

Every time when the value of that property will be set by the assertion, the `set` method will be called, as well as call to your external API. However, `observe` is much better, because `set` is called by every assertion, but `observe` is called in the RAF queue only when `set` actually changes the value of the property.

The `observe` method should be treated as an action, which has to be done to update the state of something outside of the property to be in sync with the value. For example, the `render` factory uses `observe` method to update the DOM according to the current value of the property. It is one-time action, which should not require cleanup before next call.

**Comment by rubixibuc** [comment]
Makes perfect sense, I didn't think of those other solutions

Ty for the thorough explanation!

**Comment by smalluban** [comment]
I try to understand your idea in your code example, but I still cannot find a real use case for that.

If you want to notify the outside world that your component's property has changed, you should use DOM events for that. The library has the`dispatch` helper function, which allows do it in a simple way. Then you can attach your external API and listen for the events. In that case, the `observe` is the best choice to do that:

```javascript
{
  observe: (host, value, lastValue) => {
    dispatch(host, 'property-changed', { detail: { value, lastValue } });
  }
}
```
Then in the template you can simple do:

```javascript
html`
  <my-element onproperty-changed=${myAction}></my-element>
`
```

Or even in JS, if you have reference to the element:

```javascript
const el = document.getElementById('my-element');
el.addEventListener('property-changed', myAction);
```

**Comment by rubixibuc** [comment]
I just realized now that since I'm passing the host it get's all of the props anyway. So in this case It's **not** necessary. I still think it could be useful in certain cases, but I no longer need it to serve my use case I think.

Ty for explaining to me the logic behind each other event callbacks!
