### ISSUE TITLE
Use lit-html internally

### ISSUE THREAD

**Issue by DavideCarvalho** [hybridsjs/hybrids#11]
Instead of having your own html template literal, maybe it would be better if hybrids used a famous lib for it. It would help people when looking for documentation about how to write it.
Lit-html is backed by polymer as well, and its html and render api are already stable.

**Comment by smalluban** [comment]
`lit-html` is still in rapid development. They recently merged core and extended library, changed syntax, etc. In the time when I was creating template engine (from March to May) it was really different, and in my opinion really confusing. They had a lot of issues about how to use it, or that people does not understand why something was not working (like missing the fact of extended version, which had to be used). 

The main reason behind creating own implementation was a different public API. The hybrids solution favors using element context as a main argument of event listeners, gives a user full power without need to use additnal tools (as detectives for class and style introduced lately in lit). 

Hovewer, as the hybrids is very flexible library, there is nothing to stops you from using `lit-html` with the library. The only thing you have to do is a little wrapper over render factory, as the `html` method in lit returns TemplateResult, not an update function.

**Comment by smalluban** [comment]
Is there anything else I can help you with this subject your welcome to ask :). If no, I will close the issue.

**Comment by dredzone** [comment]
Can you provide an example how lit-html or hyperhtml render can be used instead of default?

**Comment by smalluban** [comment]
Sure!

https://stackblitz.com/edit/hybrids-lit-html-counter?file=simple-counter.js

Instead of passing directly template result (using the built-in engine), for lit, you simply wrap a function with `lit()` function and use `html` from `lit-html`. For simplicity, it is re-exported in the wrapper file - `lit.js`.

I put some comments to explain why something is done in that or another way. Some of the API differences force to not use destructuring and require passing context to the event listener.

**Comment by dredzone** [comment]
very helpful, thanks for quick response.
