### ISSUE TITLE
Observing changes to children/other solutions to this problem

### ISSUE THREAD

**Issue by darrickyee** [hybridsjs/hybrids#113]
Hi, I am trying to implement some animated behavior and probably struggling a bit to get out of my "imperative" mode of thinking with lifecycle callbacks.  I'd like to implement an element that displays messages/notifications, which are added to the state one at a time.  The desired behavior is:

1. When a message is added, it plays an animation (e.g., fade in, then out after some predetermined amount of time).  When the animation ends, the message is "gone" (ideally, removed from local component state).

2. If a new message is added while others are currently visible, it should be added below the last currently-visible item.  When a previous message finishes its animation and is removed, all remaining messages should move "upwards" to fill the space vacated by the removed item.

I have an example working (I think) [here](https://codesandbox.io/s/intelligent-shadow-ks7o8?file=/src/index.js).  You can test it by clicking the "Add a message" button multiple times.  It's not perfect, but I think you get the idea.

I am wondering if there is a more efficient or elegant way to implement this.  My implementation uses absolute positioning for the message items based on the item's index in the array of items in the parent.  This means that the item element needs to have a reference to the parent, while the parent also needs references to the child elements, which seems awkward and may lead to bugs?

I could avoid this by having the parent (`MyMsgGroup`) assign the `index` property on each of the children any time the `items` (children) array changes, but I am not sure if it is "kosher" or safe to attempt to add an `observe` function to the result of `children`.  Or maybe I am thinking about this in completely the wrong way, and there's a more obvious solution?

Any help would be appreciated!

**Comment by darrickyee** [comment]
Not urgent on my part, but still wondering if you have any thoughts on this?

**Comment by smalluban** [comment]
Hi @darrickyee! I had quite a busy week, so sorry for the late response. 

We can look at your problem from a wider perspective. After all, you must choose where you want to control data. You can either control them from the outside, or inside, but you can't have both mixed together. This is a very similar problem to forms in React. If the input form is controlled, then its value is set only by the parent. Otherwise, it is provided by the input (but the view must not change its value).

If we now look at your specific use case, I would suggest controlling data from outside of visual components (for displaying the message and animate it). Then, when the data is added or removed should be delegated to the element, which renders those messages - so, it is like the input field, that dispatches `change` event, when the user presses a key or something. In your case, you can dispatch `complete` event, when the animation ends, but for the better UX, you can also attach that event when the user clicks on the message (usually it means that the user wants to close it).

I prepared a working example with that approach, you can find it here: https://codesandbox.io/s/toast-component-group-controlled-version-zd2bf?file=/src/App.js

I think what you really need, is the ability to pass new messages from any place of your application, not only from the parent element. I'm currently almost on the finish line with the store feature (writing the docs). The implementation is complete, so I also prepared an example, where instead of the local msg list, I use the store to handle data management. Then, you can simply add a new message wherever you want, and your msg will be displayed. You can find it here: 

https://codesandbox.io/s/store-toast-component-group-controlled-version-jnqm7?file=/src/App.js

**Comment by darrickyee** [comment]
Hi @smalluban, thanks for the detailed response!  You're right that in the "real" application, messages will live and be added by something outside the parent element (mobx state tree currently, but might explore other options, like your upcoming store!).

I think my difficulty in this specific case (and the reason for my convoluted solution) was mostly about the need to mutate existing elements rather than re-rendering new ones whenever the `items` array was invalidated.  Re-rendering appears to mess up the animation timers and also prevents the CSS `transition: transform [etc.]` from working properly.

I see in your example that the solution is to use `key` from the templating engine - so I ended up using lit-html's `repeat` directive and it seems to work (but it's somewhat more verbose).

Thanks very much for the help!

**Comment by smalluban** [comment]
@darrickyee The store feature is live, so you might want to look at the [docs](https://hybrids.js.org/store/introduction) and try it ;)
