### ISSUE TITLE
Property of 3rd party dependency becomes read only

### ISSUE THREAD

**Issue by suspiration** [hybridsjs/hybrids#118]
Stackblitz here: https://stackblitz.com/edit/js-zpstvd

I'm loading flatpickr and initializing it within hybrids.  The initializing works outside of hybrids, however when wrapping it in hybrids inside connect, it seems to have converted the flatpickr's property into read only.

**Comment by smalluban** [comment]
Hi @suspiration! If you use property factory for objects, their values are frozen [according to the documentation](https://hybrids.js.org/built-in-factories/property#transform-types). In your case, the property factory is used because of translation feature, so your `flatpickrConfig` definition is equal to `flatpickrConfig: property(...)`. 

The problem lays on your external library, which uses the config object for setting an internal state after the input is initialized. Instead of creating each property directly in your component, I recommend creating specialized factory for `flatpickr` integration. It not only avoids that problem but also allows using it multiple times just by one property, with your result.

It should like like this:

```javascript
import flatpickr from "flatpickr";

function flatpickrFactory(query, config) {
  return {
    connect(host, key) {
      host[key] = [];

      if (host.render) {
        const fp = flatpickr(host.render().querySelector(query), {
          ...config,
          onChange: (selectedDates) => { 
            host[key] = selectedDates;
          },
        });

        return () => fp.destroy();
      }
    },
  };
}
```

Still, you must be aware, that `connect` method is called only once, so if your template renders input conditionally it won't be initialized again. The `ref` idea described in the docs is mainly for exposing internal DOM elements as a public API of the element.

The working example you can find here: https://stackblitz.com/edit/js-5gjo3i?file=index.js

**Comment by smalluban** [comment]
I'm closing the issue, but feel free to reopen or comment if you need more help.
