### ISSUE TITLE
Standard way to setup events

### ISSUE THREAD

**Issue by xAKLx** [hybridsjs/hybrids#127]
There is no standard way to set up a property to behave like an event. We can simply pass a function (by creating a property with an empty connect) but if we start the property with "on" the function will not get assigned as it will get intercepted by the builtin addEventListener. This is what I did for now:

### Component with the event
![image](https://user-images.githubusercontent.com/13247922/90340346-7f914680-dfc5-11ea-83c4-48342592be31.png)
![image](https://user-images.githubusercontent.com/13247922/90340353-8c159f00-dfc5-11ea-96ed-f1bbbfd47c6a.png)

### Utility to create an event callback:
![image](https://user-images.githubusercontent.com/13247922/90340368-a2bbf600-dfc5-11ea-976e-df62f85b42be.png)

### Providing a callback for the event:
![image](https://user-images.githubusercontent.com/13247922/90340381-bcf5d400-dfc5-11ea-9ace-b931963c97df.png)

**Comment by xAKLx** [comment]
I created a better factory, works like the first one but it doesn't interfere with the standard addEventListener:
![image](https://user-images.githubusercontent.com/13247922/90458051-48a55880-e0cb-11ea-802e-62029d77faa0.png)

![image](https://user-images.githubusercontent.com/13247922/90458077-59ee6500-e0cb-11ea-97b9-a93c3214eeb8.png)

**Comment by smalluban** [comment]
I suppose that you came from the React-like library world ;) The custom elements provide a standard way to dispatch and listen to custom events. I must admit, that events are not documented very well in project docs. However, despite the difference in how the elements are defined by the library, in runtime, they are instances of the HTMLElement prototype, just like other custom elements. 

In your example, if you want to allow listing for the "pageclick" event, you should dispatch it when needed. Then by the standard way, you can listen to this event through all of the DOM (not only by setting function directly):

```javascript
import { dispatch } from "hybrids";

function dispatchPageClick(host) {
  dispatch(host, "pageclick");
}

const ArticleList = {
   ...,
   render: () => html`
      ...
      <li onclick="${dispatchPageClick}">...</li>
   `,
};
```
Consumer:

```javascript
function myCallback(host, event) {
  // this is called when <li> is clicked
};


const OtherElement = {
  render: () => html`
    <article-list onpageclick="${myCallback}"></article-list>
  `,
};
```

The above `dispatch()` function is just a helper, which creates `CustomEvent` and dispatches it with `host.dispatch()` method.

The standard way is much better because it behaves just like ordinary elements. For example, you can also programmatically listen for events:

```
const articleList = document.getElementById('mylist');
articleList.addEventListener("pageclick", ... );
```

**Comment by xAKLx** [comment]
That's great! thanks for the help. I will still use the factory I created as a shortcut: (this time using your dispatch utility)
```javascript
import { dispatch } from 'hybrids';

/* Will connect an event to the property instead of using addEventListener
  eventFactory: A function which receives variable arguments and returns a data to be appended to
  the event result as the detail property
*/
export function connectEvent(eventFactory) {
  return {
    connect(host, key) {
      host[key] = (...args) => dispatch(host, key.slice(2), { detail: eventFactory(...args) });
    },
  };
}

```
