### ISSUE TITLE
Ability to use HTMLFormElement and HTMLTableElement

### ISSUE THREAD

**Issue by zunwebs** [hybridsjs/hybrids#144]
I understand that the hybridsjs library supports const sturctures as custom elements through the define method. 
However i would like to create customElements using HTMLFormElement and HTMLTableElement native features still taking advantage of hybridsjs.
I could see examples for supporting form-elements in the Hybrids-ecosystem, 
1) is there a similar way to get support for HTMLTableElement/HTMLFormElement on the hybrids ecosystem , or am i missing the thinking-hat.!!

**Comment by smalluban** [comment]
Hi @zunwebs! Currently, the only supported base class is HTMLElement, as descriptors can be merged or used in other definitions. Because of that descriptors cannot rely on a different base class than HTMLElement. Its functionality could be broken if you would use them in the wrong context.

You can find more here: https://hybrids.js.org/#/getting-started/concepts?id=customized-built-in-elements

However, it is technically possible to extend `define(tag, hybrids)` function with the third argument as a base class. Still, I am not sure if it is a good idea ;) Can you explain your use case? Is it not possible to wrap a table or a form element inside of your element?

**Comment by zunwebs** [comment]
Hi @smalluban I can for sure wrap the table inside of my element however I won't b able to use a lot of inbuilt methods of the HTMLTableElement or HTMLFormElement 
That makes it easy for me to play with the data and more importantly manage a lot of manipulation events of the form or the table .
If I wrap it in my element  , I have to kind of rewrite a lot of what is already implemented and supported by the browsers as part of the specs 

Summary of my use case 
To have a generic form and table to which I can pass in a Json from outside/API call to create the table or form cynically and then eventually have event subscription on the manipulation of this element

**Comment by smalluban** [comment]
I forgot about another reason. Safari does not support customized built-in elements. And they have some real reasons behind that decision.

In your case, when you want to decorate a form with new features, you can try to create a custom element, which requires that a form is its children. When it is connected, it can take that form and manipulate it. For example:

```js
const DecorateForm = {
  form: {
    get: (host) => host.children[0], // You can detect errors here, so there is a child, and it is a form
    connect: (host, key) => {
      // decorate form here
     const form = host[key];
    },
};
```
```html
<decorate-form>
  <form></form>
</decorate-form>
```

If you have full control over the form creation, you can also simply turn off the shadow root option, so the render will take place in the light content of the element (as working with forms in Shadow DOM is harder).

**Comment by smalluban** [comment]
@zunwebs Feel free to reopen if you have any other questions about the subject.
