### ISSUE TITLE
Object references in render-templates does not re-render the element on value changes : using store across multiple instances of the webcomponent #126

### ISSUE THREAD

**Issue by zunwebs** [hybridsjs/hybrids#157]
HI @smalluban  : taking further on issue #126 , [issue](https://github.com/hybridsjs/hybrids/issues/126)     
I tried using the store feature where I could set and retrieve values from for the item variable however the store ends up returning the same value for all the instances of the web component .
So anywhere and everywhere the the web-component is used on the page , the same value of item reflects.
I think I am doing something wrong with manipulating the value .

I had an id (uuid) field already on the Item model which I had to comment since hybrids errored out . And I understand that hybrids will auto assign it for each object added to the store .
To update the value of item in the store I just use store.set(item,{ item properties with new values})
However with this I am unable to figure out as to
3.1 : will the store have only 1 instance of the item value (for all instances of the web component being loaded)
3.2 if in case if has different instances , how to access the particular instance of item from the store which was created in the store for the web-component instance in question, since the id is auto populate by hybrids there is no reference to it for me in the host for track if for pushing an update on the same instance of item in the store .
Please let me know if I am missing on any documentation/concepts that I should've referenced

**Comment by smalluban** [comment]
Hi @zunwebs. Store models are global by design, so if you use the same id (or model without id) all of the web components will share the same model instance. If you want to create a form for creating new model, you should use `draft` mode of the store factory. It allows to generate unique memory located model clone for the form, and then pass to the original model by the `store.submit()` method:

```
MyModel = {
  id: true,
  value: "",
};

MyForm = {
  model: store(MyModel, { draft: true }),
  ...,
};
```

Even though normally the store requires setting the `id` option (as `id` field of the object, or property name) if you set `draft` mode, then without `id` the store will create a new model instance when submitted.

**Comment by zunwebs** [comment]
`Even though normally the store requires setting the id option (as id field of the object, or property name) ` 
=** in this case, do I also have the provision to assign the id  for the model myself from the code , that way on the web-component instance I always have a reference to what should I look for in the store .

**Comment by smalluban** [comment]
Can you provide some code example, which does.not.work for as you would expect? Sorry to tell, but I can figure out what do you mean in your last comment :)

**Comment by smalluban** [comment]
Feel free to re-open, if the problem still exists, and you can provide example, so we can solve it together :)
