### ISSUE TITLE
Suggestion for implementing astro renderer

### ISSUE THREAD

**Issue by kostadinnm** [hybridsjs/hybrids#171]
Hello.
There's this new scaffolding framework [astro](https://github.com/snowpackjs/astro), which is super promising for partial hydration, imho. It's an uplift of snowpack by its creator(s). If this happens to be so powerful, it might be a good idea to develop an `astro renderer for hybrids`.
Where did github discussions go?!

Cheers,
Kostadin

**Comment by smalluban** [comment]
I think this is a good place to start a discussion about it :) There is a closed issue https://github.com/hybridsjs/hybrids/issues/154 about declarative shadow DOM, which covers some parts of the subject. 

As you can read there, hydration is complicated more because how you serialize state of the components, not just render their content DOM ;) Still, I think it might be the next big feature, which I will work on :) Of course after the router.

**Comment by smalluban** [comment]
I am not planning to introduce SSR in the next few months, so I am going to close the issue for now. When the feature will be ready, I'll be back here to discuss options.
