### ISSUE TITLE
Nested arrays and objects in store could use more 'splaining

### ISSUE THREAD

**Issue by chasm** [hybridsjs/hybrids#177]
Examples would be nice. Lot's of 'em. Do they exist somewhere? That might help uptake.

I have a JSON configuration representing a DOM tree. Objects have `children` values which are arrays of similar objects. These can be nested **arbitrarily deeply** -- figure typically a dozen or more levels in the tree.

Ideally, I'd like to load this into the store of the top object -- the renderer. I have figured out (somewhat painfully -- see note about _examples_ above) how to get back the children, but only by specifying them again and again. How can I nest arrays of child objects _arbitrarily deeply_ without ending up with "[Object object]"? I do not want to go back to the server to get bits and pieces. I want to load the config once, recurse down the tree, and render the components. Is this doable with hybrids? It's pretty much make or break for me.

Also, these objects are _similar_, but not identical. Each represents something in the DOM. It would be nice, actually, to be able to model them individually, and then to permit only certain models to contain children, and then only certain children. Ideas?

Can't say that I find the hybrids code easy to read and work with, but it's nicely declarative and easily the best web component library I've tried so far. Nice work. I could go back to React, but I'd love to make this work with something simple and blindingly fast (i.e., no virtual DOM). Hybrids looks like it might be a good choice.

**Comment by smalluban** [comment]
Hi @chasm! It will be easier to help you if you provide some code examples of your structure. The store by design requires a strict definition of the model upfront. The main purpose of the store is to keep the data, which typically has a static type of structure. 

I am not sure if the store is the best option to save the state of the DOM tree, but there are some features that might help you. For example, there is `store.ref()` which allows creating circular references. For polymorphic relations, I can recommend creating a proxy model (which can reference different types of data) or extend the model with all required fields (by all of the types).

```javascript
import { store } from "hybrids";

const Node = {
  prop1: string;
  prop2: number;
  children: store.ref(() =>[Node]),
};
```

**Comment by chasm** [comment]
Thanks. That was my thinking. I'm not actually saving the state of the DOM tree, but that ref trick will no doubt be useful.
