### ISSUE TITLE
Hybrids SSR

### ISSUE THREAD

**Issue by DavideCarvalho** [hybridsjs/hybrids#24]
I was studing SSR with WebComponents, and it's quite easy with Web Components, i just need to use ```new Component()``` with my component class with skatejs library and it's done! I'd like to know if hybrids' define method returns a class so I can do SSR with Hybrids.

**Comment by smalluban** [comment]
Yes, it does, but only if you use `define` function. However, it not only creates a class, but also use `customElements.define` to register it in the document. I think you want to avoid it on the server side.

When I was designing API, I haven't SSR in mind, so I assume that the library will be only executed in the browser environment. Because of that, some of the factories calls DOM APIs on the module level, for example `parent` factory [here](
https://github.com/hybridsjs/hybrids/blob/master/src/parent.js#L3). Also, I encourage you to look at the #18 issue. It explains lazy approach to render in the hybrids. I think, that your skatejs solution, would produce empty internal structure (if you would have your requiered class).

Of course, you can experiment with SSR if you want. With current code you need to polyfill `document.addEventListener` and `customElements.define` methods - they don't have to do anything, just define them in global scope. With those changes, you can call `define` function from the hybrids, and this function returns class constructor, which you want.

**Comment by DavideCarvalho** [comment]
I tried doing it with Hybrids, and a error was thrown
![image](https://user-images.githubusercontent.com/15630886/48631564-f8eda680-e9a5-11e8-8f43-161d1a118d73.png)

**Comment by smalluban** [comment]
I didn't mean that it is easy :P. Unfortunately, I have no time now to focus on SSR. I am in the middle of a big rewrite of the documentation. 

What I can recommend you is to follow errors and try to create structures that will fix them. The attached screenshot shows that event listener callback requires the event argument to support composedPath method. 

I think you may try to use dom-js or another project, which adds DOM API to the nodejs. 

If you find a solution feel free to re-open and show your results! Happy coding!
