### ISSUE TITLE
property: Reflecting properties back to attributes

### ISSUE THREAD

**Issue by therealnicksaunders** [hybridsjs/hybrids#26]
Per [Google's Web Fundamentals](https://github.com/google/WebFundamentals/blob/master/src/content/en/fundamentals/web-components/best-practices.md#--aim-to-keep-primitive-data-attributes-and-properties-in-sync-reflecting-from--property-to-attribute-and-vice-versa--------): _Aim to keep primitive data attributes and properties in sync, reflecting from property to attribute, and vice versa._

Is this a thing yet, or no?

My first thought was that I could just implement a custom property descriptor factory that includes this behavior; but I quickly realized that a side-effecting behavior such as this does not belong in a set function.

**Comment by smalluban** [comment]
I designed descriptor API to be as simple as possible. Because the set method has no access to `key`, it is not possible to get this value and pass it somewhere - especially do something like `host.setAttribute(key, value)`. But, what it would then...? A side effect, which breaks idea to use pure functions. They should not mutate host object in get, or set methods. 

The architecture behind the library required out of the box patterns, which still are consistent with Web APIs. And hybrids approach reflects what is already in HTML specs - all types of `<input>` element treat `value` attribute as default and dynamic value changes only with setting `value` property.

I looked at the document you linked:

> You never know how a user will interact with your element. They might set a property in JavaScript, and then expect to read that value using an API like getAttribute()

How we can not know how users will interact with our element ?? It should be explained in the component documentation, so this argument does not go to me. 

Another example:

> Create your shadow root in the constructor.

Hybrids also breaks this rule with `render` factory. And again this is a result of making descriptor simple - there is no `construct()` callback, only `connect` and `disconnect`. But, this is what the library is doing for you, so you don't have to worry about it.

One of the main goals of this library is to make things simpler - there is no "never know" - attributes are for static values - and they have to be translated from string (so there is also a cost here), properties are for dynamic values.
