### ISSUE TITLE
lagging update glitch

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#265]
example: https://codepen.io/qsppl/pen/WNqXLGO

The observed behavior is not obvious. The first time library users encounter this behavior, it will be confusing.

**Comment by smalluban** [comment]
You must not use setters inside of the `value` function - as may create an endless loop of actions. You should use the `observe` method, to take action when one property change should influence another.

However, thanks for pointing it out, I made a fix, and release new version, which will throw for your example code.

Instead of setting a value while getting another, you should use `observe`:

```js
{
  one: {
    value: 1,
    observe: (host, value) => { host.two = value },
  },
  two: undefined,
}
```

**Comment by Qsppl** [comment]
Thank you, now it has become much easier to notice the error and understand why it occurred.
