### ISSUE TITLE
Hybrids Component within React

### ISSUE THREAD

**Issue by ides15** [hybridsjs/hybrids#46]
Hi! I'm trying to use Web Components as a way to abstract parts of my UI from the parent site.

I'm trying to understand how Hybrids can turn a React component into a custom element, and then have the parent site use that element, _especially_ in development.

![image](https://user-images.githubusercontent.com/17836075/54871678-a6c2f480-4d8e-11e9-9e37-34c6e7e11ad5.png)
This is the general architecture of what I'd want my site to look like, and be able to add new (fairly complex) web components into the parent site.

Is Hybrids able to do this? I've just started playing around with Hybrids and saw the react-counter example, but there it was using the custom elements within an `index.html` file. Can my parent site (React) use those custom elements while they are being developed alongside the parent site?

Really, really cool library btw.

**Comment by smalluban** [comment]
You can wrap anything that produces update function according to `render` factory specification and use it as a renderer.  However, Vue and Angular have own projects, which allow targeting custom elements (I mean creating Vue or Angular components and generate custom element). You don't have to use hybrids for it. It does not have so much sense. 

React is another story. Its web components support is very weak. It only supports passing attributes (no luck with properties) and does not support listening to custom events. There are projects that wrap **custom elements** into React components - to be able to work with React application (You can read more here: https://github.com/hybridsjs/hybrids/issues/15#issuecomment-430525315).

From your picture, I understand that you want to overengineer your solution. You would have to create a uneccesery chain of wrappers to make it work as you draw:

React app <-- ReactCustomElementWrapper <-- HybridsWrapperToCustomElement <-- YourReactComponent

Instead of:

React app <-- YourReactComponent

If your primary application would be Vue or Angular, it will be seamless - you can use your web components just like that (in Angular I think you have to declare your custom elements names additionally).
