### ISSUE TITLE
[Proposal] Create hybrids app

### ISSUE THREAD

**Issue by ValeriaVG** [hybridsjs/hybrids#48]
I believe this project is awesome and deserves an easy to use generator similar to `create-react-app`.

I created a [starter project with webpack, babel & jest ](https://github.com/ValeriaVG/hybrids-starter-kit).
Once it looks good enough I can add a script to generate the folder to use it with `npx`.
I would really appreciate some feedback on that, thank you!

**Comment by smalluban** [comment]
Thanks for the nice words about the library. I will try to look into the code of your project. If I find something I will add an issue there. 

Hybrids is still more a library for creating WC rather than a framework for whole apps. There is a lack of routing and more sophisticated state management, especially for async data. Because of that, I am not sure about creating whole apps only based on hybrids. You can consider adding other libraries based on web components to support that.

**Comment by ValeriaVG** [comment]
Yes, I see your point. It is supposed to support other web-components out of the box since it has all the polyfills. But I’ll test it. Also I’m not sure that the routing should be done through the shadow dom and hence any js routing library should be able to handle with it.

**Comment by DavideCarvalho** [comment]
I don’t think the lack of state management and routing makes it hard to make an app. React works like this too.
I made an app for a friend using Hybrids and other libraries, and using a micro frontend like approach

**Comment by DavideCarvalho** [comment]
Instead of doing a cli, we can use degit for now.
Degit creates a project based on a github repo.
Svelte uses it to create projects.

**Comment by smalluban** [comment]
Looks promising. We could then document it like:

```bash
npx degit hybrids/simple-app
```
My recommendation for simple scaffold would be a project build with parcel bunder, and a custom plugin for importing styles from separate files support (it might be created in hybrids organization. Parcel assumes that styles are global and put them in head, so out of the box you can't load them as a plain text using import statement).

However, I still think that people expect, that app skeleton provides state management and routing (which both I have in my road map, but they are not ready yet).

**Comment by DavideCarvalho** [comment]
I still disagree on what people expect from a scafold. Neither React, Angular or Vue has a scafold with everything avaliable (since Angular and Vue have cli, you can opt for it tho).
But we can create a simple scafold and another scafold with routing and state management.
To make sure the scafold is running, maybe is worth making a CI with Cypress

**Comment by ValeriaVG** [comment]
I'm actually leaning to the idea of having two separate scafolds: for a single component - capable of packing web component for distribution - and for an entire app.

I tend to agree that hybrids (being web-components after all)  should keep the ability to be easily shared and be framework agnostic.

Still, having a "default way to go" will drastically increase interest in the library and web-components overall.

**Comment by xdvarpunen** [comment]
Use CLI for communication between team and Degit or/and CLI for project setup (replace cli init parameter with Degit). Main issue I see in Degit is that getting things done requires study of project structure which takes time. CLI could by pass this necessity and let just get things done. So my answer: both CLI and Degit.

**Comment by threeid** [comment]
Yeah! Please make CLI tool to bootstrap a Hybrids.js app.

**Comment by smalluban** [comment]
@ValeriaVG I am closing this issue. I described my recommendation about how we can go with a project for bootstrapping hybrids apps. Fill free to create another one, if you would like to share or ask about something related to your project directly. 

I have a strong intention to create an ecosystem for using hybrids web components for building applications, but it requires work which is ahead of my schedule now.
