### ISSUE TITLE
Running DOM updates after rendering

### ISSUE THREAD

**Issue by Avnerus** [hybridsjs/hybrids#56]
Hi!
Apologies up-front if this question is already answered in the documentation or in another issue, but I couldn't find a direct answer to my problem.
Imagine I have `<log-transcript>`  - a scrollable component that is connected to an array of log lines from a redux state, and renders the log whenever a line is added, something like this:

```
export default {
    transcript: connect(store, (state) => state.transcript),
    render: ({transcript}) => { 
       return html`
        <style>
            #transcript-container {
                overflow: scroll;
            }
        </style>
        <div id="transcript-container">
            ${transcript.map(( line ) => html
                `<div class="transcript-line">${line.text}</div>
            `)}
        </div>
     `
   }
}
```
Now I would like to have the element automatically scroll down to the latest line upon update. 
This is done using:
```
 container.scrollTop = container.scrollHeight;
```

But it must be called after the container has the updated `scrollHeight`. Where would the appropriate location for this code? So far I could only work around this by calling a function from `render()` and using `setTimeout(0)`.

Thanks!

/Avner

**Comment by smalluban** [comment]
> Apologies up-front if this question is already answered in the documentation or in another issue, but I couldn't find a direct answer to my problem.

You are always welcome to create an issue, if you want to know something about the library, like anyone else :)

Your problem is an excellent example of how hard it is to start thinking in another way. At first, it might look that your question shows a gap in API, because you can't invoke side effect after the DOM is rendered. The library decoupled it - the component should be a declarative definition of inputs (properties) and output (rendered DOM).

Manipulation of the DOM after input change should be a side effect of the output (DOM). However, in your code example, you are trying to match the input with a side effect.

Let's think again what is your goal. You want to have an element which scrolls to the end when new element appends. Instead of creating it as a div element inside of your main component, try to create a separate custom element. Why? You can use mutation observer built-in `<slot>` element. The `slotchange` event is triggered when children put in slot changes. Then in a function of that event listener move scroll position of the host to `scrollHeight`.

```javascript
function scrollToBotton(host) {
  host.scrollTop = host.scrollHeight;
}

const ScrolledLogger = {
  render: () => html`
    <style>
      :host { display: block; overflow: scroll; }
    </style>
    <slot onslotchange="${scrollToBotton}"></slot>
  `,
};
```

Your main element (uses `scrolled-logger`):

```javascript
export default {
    transcript: connect(store, (state) => state.transcript),
    render: ({transcript}) => html`
      <scrolled-logger>
          ${transcript.map(( line ) => html
              `<div class="transcript-line">${line.text}</div>
          `)}
      </scrolled-logger>
   `,
}
```

**Comment by smalluban** [comment]
Feel free to reopen if you encounter any problems with the subject.

**Comment by Avnerus** [comment]
Hi!
Sorry for disappearing. I was actually out field testing the project that I am using Hybrids for, and never got around to try your suggestion
I just tried it now and it does work! Thank you for that.
I am still not sure how I feel about the need to define another component and use the slot mechanism just for handling this kind of 'side-effect'. It's definitely nice to be able to use the standard HTML/ShadowDOM interface, but it also complicates the code relative to the amount of functionality added.
I noticed for example that in React-Hooks they allow this within the functional component with ['useEffect'](https://reactjs.org/docs/hooks-reference.html#useeffect). What do you think about that kind of approach?  
Thanks again!

/Avner

**Comment by smalluban** [comment]
`useEffect` or another internal tool ties the code to your component definition.  It will only work in specific conditions. In my proposition, you can do the opposite. 

Imagine that we have a built-in element, which scrolls position to bottom when you add children to it. Would you use it? Or instead, you would create `useEffect` thing (the custom solution with a div or another element)? I would choose the first one, and I think you too. When it is possible, we want to use the "platform" because it is the easiest and safest way (we are more confident that it will work in all browsers, which supports it). Unfortunately, in this case, we don't have that element so that we can create it. It is a general-purpose element, which can be used anywhere - or even made public on npm or another repository - it is not strictly related to your logger component.

That's the philosophy of building web components. Even though the solution might look tricky (using special event) - it uses "platform" as much as it can and provides a solution easy to reuse, test, and share.

The hybrids library, on another hand, tries to avoid sequential code. Side effects should be really "side". It means that they should be called because of external interaction (then they change internal part) or internal parts trigger them, but then they update something outside of the component.

**Comment by Avnerus** [comment]
Yes, I definitely agree with the general approach. It is only perhaps the fact that the functionality of scrolling to the bottom seemed so small to me for creating a component, even if it's a generic one, because I was imagining the mess it might create when more side effects are required. I guess in time I will see whether this approach is scalable, for now it's definitely good enough. Thank you again for all of the help!
