### ISSUE TITLE
Rendering WC into VueJS

### ISSUE THREAD

**Issue by akoushke** [hybridsjs/hybrids#62]
Love your library btw! keep up the good work!

### My Problem with Hybrids
This might not be an issue but a bug from my side, but your help is greatly appreciated. I'm trying to wrap some react components into web components to offer them to all non-react developers.
what the code does is basically grab all react components and create a web component wrapper for each. it then formats the object and passes the formatted object to your fine `define` method.

```js
import {define, render} from 'hybrids';
import * as Components from '@momentum-ui/react';
import React from 'react';
import ReactDOM from 'react-dom';

// Grab all of the momentum-ui react components
const webComponents = Object.keys(Components).map(key => {
  // Convert the PascalCase string with lowercase string plus dashes in between
  const name = `web-comp${key.replace(/[A-Z]/g, m => "-" + m.toLowerCase())}`;
  const component = {
      render: render(() => {
        // Grab the react component whenever being invoked
        const Component = Components[key];
    
        return (host, target) => {
          // Render the component with the given properties
          ReactDOM.render(<Component {...host} />, target)
        }
      },  { shadowRoot: false }) // No to Shadow DOM
    };

  return {name, component};
});

const formattedWebComponents = webComponents.reduce((result, item) => {
  const component = Object.keys(item)[1];

  // web-comp-avatar: Avatar Constructor
  result[Object.values(item)[0]] = item[component];
  return result;
}, {})

define(formattedWebComponents);
```
This solution works fine in `Angular`. However, `Vue` application does not pass the properties accordingly. they are all `undefined`.

my Vue.js application:
```js
import Vue from 'vue';
import './momentum-ui.scss';
import '../../../web-components';

Vue.component('app', {
  data: () => {
    return {
      src: 'https://8e325148c33e40909d40-0b990d1d119de8e505829619be483465.ssl.cf1.rackcdn.com/V1~47c32d0b-0444-460d-8bce-2265b501aac5~bfc8719afb284d998b25362fbffc7d43~1600',
      type: 'active'
    }
  },
  template: `
    <div className='parent-container'>
      <web-comp-avatar 
        :src="src"
        :type="type"
      /> 
    </div>`
})


new Vue({ 
  el: '#components-demo'
})
```

**Comment by smalluban** [comment]
It is a very interesting case :) How to start... Hybrids uses prototype mechanism to define properties, and they are getter/settter properties. In JavaScript when you set the value to those properties, instead of creating own property (on the top object instance), the set method from the prototype is called. It means that the instance still does not have own property... Now, let's see your code. In your example you are passing host properties into the React component using spread operator - by the definition, it only passes "own" properties, so it should not work at all. However, why does it work in Angular? It should not work too, but if it really works it means that angular has a problem and not use the prototype (proper assertion, using '=' operator), but set property by `Object.defineProperty()` method and does it on the instance (which would stupid by the way).

The second problem of your WC generator is that you don't define input properties - so hybrids will not re-render your component when they will change... Hm.. It might be a answer why it works in angular, but not in Vue - they might pass properties at a different moment in time - the first before appending to the DOM, and the latter after. Hybrids renders your template for the first time with (Angular) or without (Vue) properly set properties.

How you can fix it? Your React components should inform what kind of input properties they use. If you don't care about types, you can define them all with `undefined` value in hybrids component definition, but you have to do this. Then, if you will have a list of input properties, you should explicitly pass them to React component rather than using the spread operator. I think static propTypes can help you with that.

```javascript
// Grab all of the momentum-ui react components
const webComponents = Object.keys(Components).reduce((acc, key) => {
  // Grab the react component whenever being invoked 
  const Component = Components[key];
  const inputProps = Object.keys(Component.propTypes);

  const component = {
    render: render(() => {
        return (host, target) => {
          const props = inputProps.reduce((acc, key) => {
            acc[key] = host[key];
            return acc;
          });
          // Render the component with the given properties
          ReactDOM.render(<Component {...props} />, target);
        }
    },  { shadowRoot: false }) // No to Shadow DOM
  };
    
  // Define input props of the React component
  inputProps.forEach((key) => {
      component[key] = undefined;
  });

  // Convert the PascalCase string with lowercase string plus dashes in between
  const name = `web-comp${key.replace(/[A-Z]/g, m => "-" + m.toLowerCase())}`;
  acc[name] = component;

  return acc;
});

define(webComponents);
```

**Comment by smalluban** [comment]
@akoushke Let me know if my solution works. If you don't have any other problem with the case please close the issue.

**Comment by akoushke** [comment]
@smalluban will do. Some react components from that third party library are missing prop-types. I’m trying to figure out why, but I was planning to just make this work with the other components. Will update you ASAP.

**Comment by akoushke** [comment]
I'm going to close this right now. Will update you if there was any more issues. thanks again.

**Comment by akoushke** [comment]
I'm going to close this right now. Will update you if there was any more issues. thanks again.

**Comment by akoushke** [comment]
I did have another question in terms of using `reactDom.render`. 
I'm assuming using `reactDom.render` many many times is not a best approach for a large application. However, I found that's the only way to wrap a react component into a web component. 
Obviously I'm talking about this line of code here:
```js
ReactDOM.render(<Component {...props} />, target);
```

Is there a way to come up with a precompiled html code *without* given properties? maybe I can use that html template into my web component definition and embed the props later in the runtime? That way I don't have to call `ReactDom.render` for each component. I just return the html code with given embedded properties. does this makes sense? I know that `ReactDomServer` offers html initial from a given react component. However, you will need to pass a react element first which requires props and/or children. any suggestions? I'm all ears!!!! thanks <3

**Comment by smalluban** [comment]
>I'm assuming using reactDom.render many many times is not the best approach for a large scale application.

If you plan to build "a large scale application" and use a lot of react components, it might not be the best idea to wrap them all in web components ;) The main goal of wrapping React in web components is to let users from other frameworks use particular components with a standardized way without need to use React directly. 

However, I always thought that calling `ReactDOM.render` after initial load will work the same as you would call `forceUpdate()` inside of the component. As we know, that props have changed (because of how hybrids cache works) it is the same as passing new props to the component inside of the React tree. It should not have a performance impact on your application.

There is an issue in React repo about it, which is signed as a bug, and what I read solved: https://github.com/facebook/react/issues/12700
