### ISSUE TITLE
Recommended setup to work with CSS

### ISSUE THREAD

**Issue by tovare** [hybridsjs/hybrids#67]
Hi,

In the docs, you give some setup advice, but could you provide any specific information for configuration and which tools are known to work well or a small project you can share that is set up.

My preference would be:

 1. I want to work with the import statement for CSS with a modular framework.
 2. I want to build components that are independent and minimized, component by component, so that they can be included directly on a web page.
 3. I want the reload feature while working.

I got going with Parcel and NPM, but it builds everything into one bundle, also I could only include CSS using the import URL in CSS. It seems the combination will not work well in my case.

Your framework makes a lot of sense. Thanks a lot for your effort and congratulation on a well-deserved nomination.

**Comment by smalluban** [comment]
> I want to work with the import statement for CSS with a modular framework

For now, the easiest way to use `import` statements for CSS is webpack following an example from the docs (You should use `raw-loader`, as we need a full body of the generated CSS file). The parcel bundler has built-in support for CSS, which put all of your styles in the head of the document. It works very well for light DOM, but it doesn't for passing it into the Shadow DOM.  Unfortunately, there is no simple way (ready to use parcel plugin) to re-configure parcel to pass CSS content into by the `import`. If you really like to use parcel-bundler you will have to create your own plugin, which should work similar to [parcel-plugin-raw-xml](https://www.npmjs.com/package/parcel-plugin-raw-xml) but for `.css` files.

Because of that, I recommend using webpack, where you have more control over the loaders setup.

> I want to build components that are independent and minimized, component by component so that they can be included directly on a web page.

You can create multiple entry points (using webpack) and produce a built and minified version of your web components (look at the webpack configuration of the hybrids). Then each entry point should import what it needs from hybrids, external CSS files and define a custom element with `define` function from the library. However, for users who works with NPM it would be better to import your library or even separate web components from your library. Then hybrids would be loaded only once.

> I want the reload feature while working

If you choose webpack, you can use `webpack-dev-server` with simple playground loading your definitions from other entry points. HMR works out of the box, just follow instructions from [Getting Started](https://github.com/hybridsjs/hybrids#hot-module-replacement) section.

**Comment by tovare** [comment]
Thanks a lot for the help!. I spent some time getting into Webpack and got the import working, but my source ballooned in size and Webpack makes everything more complicated and slower, so I ended up chickening out a bit on adopting webpack and friends. Eventually, I might need to figure everything out.

For now, I´m giving the following strategy a try:

The most basic Parcel set up with the command defined in package.json with the css defined as an entry to keep the name stable:

`"test": "parcel  -p 8080  watch main.css index.html"`

I link a minimalistic low-level CSS such as custom-props for colors and spacing in a main.css (defined as an entry to read it once only across all components) Write component specifics in the source using plain CSS. I plan on not using a complete CSS framework but copy and paste from good sources like tachyons.io and elsewhere.

```javascript
import { html, define } from 'hybrids';

export const LoginButton = {
    render: () => html`
      <link rel="stylesheet" href="main.css">
      <style> 
        button {
          box-shadow: 3px 3px  var(--darkshades);
          border-radius: 4px;
        }
      </style>
      <button >
        Log in! 
      </button>
    `,
  };
   
define('login-button', LoginButton);
```

I tried unbundling components by adding components/login-button and it seemed to work but I am delaying that ambition :-)

My directory layout is very simple as well (for now):

```
sportapp/
   components/
       component1.js
       component2.js
   index.html
   main.js   (Just enable HMR and component imports like in the manual). 
   main.css
```

Parcel makes a dist folder containing 
```
Built in 462ms.

dist/sportapp.940b1f4e.js.map    69.55 KB     29ms
dist/sportapp.940b1f4e.js        29.52 KB    185ms (I don´t usee the shims)
dist/main.css.map                   893 B      4ms
dist/index.html                     530 B      5ms
dist/main.css                       449 B    105ms
```

**Comment by smalluban** [comment]
I'm happy that I could help you.  The idea with external styles for commons looks nice. The only thing that you should take into account, is that external styles are not supported by the ShadyCSS polyfill (more info [here](https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#external-stylesheets-not-currently-supported)).  However, if you target browsers with native support you are good to go.

**Comment by tovare** [comment]
Thanks for the heads up and links to docs. :-) I hope that I can avoid supporting feature-challenged browsers, but I don´t know how all of this will play with Apache Cordova yet :-)
