### ISSUE TITLE
"Manually" invalidate property?

### ISSUE THREAD

**Issue by darrickyee** [hybridsjs/hybrids#77]
Hi, is there a way to directly invalidate a property without going through the "connect" on a property descriptor?

I am interested in general, but also have a specific case where I want to copy a component's slot content.  My current setup looks like this (`lit()` is from your lit-html example and `html` is the lit-html version):

```
function copySlotNodes(host) {
    const slot = host.shadowRoot.querySelector('slot');
    return slot ? slot.assignedNodes().map(n => n.cloneNode(true)) : [];
}

const UeText = {
    slotContent: {
        get: host => copySlotNodes(host),
        connect: (host, key, invalidate) => {
            host.updateSlot = invalidate;
        }
    },
    render: lit(
        ({ slotContent, updateSlot }) => html`
            ${styles}
            <div class="grid-1 bg">
                <slot @slotchange=${updateSlot}></slot>
            </div>
            <div class="grid-1 fg">${slotContent}</div>
        `
    )
};
```

Basically, the `slotContent` property is a copy of the element's slot nodes and is inserted into the template (so that I can duplicate the slot nodes).  When the slot content changes, I want to invalidate `slotContent` so that it retrieves copies of the new slot nodes.  It would be nice to be able to have the `slotchange` event directly call the `invalidate()` for the property.  Currently, I instead need to add a property at connect-time to refer to `invalidate`.

I could also define `updateSlot` as an external function that both copies the slot nodes and sets `slotContent` on the passed-in "host," but this doesn't feel as "clean" to me since the external function is no longer "pure" (i.e. it's mutating a passed-in object and would probably return nothing).

Also open to other ideas...

**Comment by smalluban** [comment]
Generally, `invalidate` is available for syncing with third-party tools, which are dependencies of the property value. If they change, we can notify the library that the property should be re-calculated if needed. It should not be returned or passed to another property in `connect()` method.

I have to say, that your case is specific (I am not sure why you have to duplicate your slot content). It is not possible to attach event listener to `slot` element in `connect()` method of the `slotContent`. By design properties are independent and in that case `slot` element is not available in `connect()` method of the `slotContent` (render is called in the queue started with `requestAnimationFrame()` API). 

However, you can use `set()` method to update `slotContent` passing `slot` element as an argument:

```javascript
const UeText = {
    slotContent: {
        // get is required only if you want to have empty array before initial set
        get: (host, list) => list || [],
        set: (host, slot) =>  slot.assignedNodes().map(n => n.cloneNode(true)),
    },
    render: lit(
        (host) => html`
            ${styles}
            <div class="grid-1 bg">
                <slot @slotchange=${({ target }) => { host.slotContent = target; }}></slot>
            </div>
            <div class="grid-1 fg">${host.slotContent}</div>
        `
    ),
};
```

It is not exactly pure side effect - we assign a new value to `host.slotContent` - but, this is how the library works - the pure functions are mainly in component definition - side effects don't have to be - and usually they don't as they change properties values (our input values).

Because you are using `lit-html` event callback has no reference to host, so in the above example, I had to used dynamic function (and I had to sacrifice destructuring in render). I recommend using a built-in template engine, where the first argument of the event callback is the host, so passing function reference works.

I think that you wanted to avoid setting directly `slotContent` value, as in the above example, but I can't find another solution right now. Still, your case is we have to rely on render content event listener, so it is right to think of that as a side effect, which updates component inputs.

**Comment by darrickyee** [comment]
Thank you, this is just what I was looking for!  It's much cleaner and more readable than my original.

I ended up modifying it slightly to assign a node array instead of an event target, to match the assigned value with the property type (`Node[]`):

`@slotchange=${({ target }) => {host.slotContent = target.assignedNodes();}}`

...which I assume is "safe" because the target should always be a `HTMLSlotElement`.

I didn't necessarily want to avoid setting a property directly, but in a simple case like this I think I'd prefer to avoid calling an external function that mutates the host in ways that aren't easy to "see."  So your solution is perfect.

Btw, my implementation of this same component in LitElement was almost 50 lines long, excluding styles!

**Comment by smalluban** [comment]
> Btw, my implementation of this same component in LitElement was almost 50 lines long, excluding styles!

Nice!

**Comment by darrickyee** [comment]
I forgot about an issue I had solved before.  Unfortunately `slotchange` only fires when the slot nodes themselves are added or removed, not when a node is mutated.  If for example I use the component above in some other component's template:

```
html`
    <ue-text>${host.value}</ue-text>
`
```
...then there's a single text node in the slot, and updating `host.value` mutates the text node's content, rather than removing it and attaching another text node.  So that change doesn't fire `slotchange`.

My previous solution was to use a `MutationObserver` on the slot nodes, and I did manage to get it working with hybrids.  But is there a more elegant way to accomplish this?

**Comment by darrickyee** [comment]
Here is my current implementation, with styles.  I wanted text that auto-outlines, with outlines on the outside only.  `-webkit-text-stroke` draws on both the inside and outside, making the text look awful.  

The simplest way I've found to do that is to draw the text twice, once with stroke and once without, overlaying the second on top of the first.

```
import { lit, html } from '../util/lit';
import { define } from 'hybrids';
const styles = html `
    <style>
        :host {
            display: grid;
        }

        .grid-1 {
            grid-column: 1;
            grid-row: 1;
        }

        .bg {
            -webkit-text-stroke-width: var(--text-outline-width);
            -webkit-text-stroke-color: black;
        }

        .fg {
            color: var(--text-color);
        }

        div {
            user-select: none;
            cursor: default;
        }
    </style>
`;
const observers = new WeakMap();
const UeText = {
    slotHTML: {
        get: host => host.innerHTML,
        connect: (host, key, invalidate) => {
            // Create observer if it doesn't exist
            const observer = observers.get(host) || new MutationObserver(invalidate);
            observers.set(host, observer);
            observer.observe(host, { characterData: true, childList: true, subtree: true });
            return observer.disconnect;
        }
    },
    render: lit(host => html `
            ${styles}
            <div class="grid-1 bg" .innerHTML=${host.slotHTML}></div>
            <div class="grid-1 fg" .innerHTML=${host.slotHTML}></div>
        `)
};
define({ UeText });
```

I had a "duh" moment when I remembered that content within the custom element in the light-DOM isn't rendered, but is still in the DOM.  So I could dispense with slots entirely and just monitor for changes in the host's `innerHTML`.  Thanks to the "smart" invalidation, the circular reference between the `.innerHTML` property and `host.slotHTML` doesn't cause an infinite loop (which I guess is the point).

Still, I haven't figured out how to "listen" for changes in the `innerHTML` without a `MutationObserver`.  This isn't a hybrids-specific issue (My LitElement implementation does the same thing), but I was thinking there might be a more clever way to do this with hybrids.

**Comment by smalluban** [comment]
I'm not sure if not using original elements is good idea. For example, if will be template something like this: 

```html
<ua-text><my-super-text @click="{...}">Click me</my-super-text></ua-text>
```

your element only copies innerHTML and put two clones inside of the shadowRoot, but all of `lit-html` event binding will be gone. You can leave as it is, but then you should restrict that content of that element only can be text. However, instead of the second copy, you can pass there `<slot>` - the effect should be the same - I am not only sure about syncing changes between copy (using MutationObserver) and slot.

> Thanks to the "smart" invalidation, the circular reference between the .innerHTML property and host.slotHTML doesn't cause an infinite loop (which I guess is the point).

Cache mechanism only "watches" properties created by the library - so `innerHTML` is not "watched" for changes - `slotHTML` updates because your `invalidate` passed to mutation observer.

> Still, I haven't figured out how to "listen" for changes in the innerHTML without a MutationObserver.

Unfortunately, there is no other way to listen for DOM changes manually, you have to use `MutationObserver`. The duplicating element content is a rather rare use case, so you should not feel bad about using `MutationObserver` API.
