### ISSUE TITLE
Running function after first render

### ISSUE THREAD

**Issue by darrickyee** [hybridsjs/hybrids#78]
Hi, sorry for the question spam, but I'm having some difficulty with maybe an unusual use case.

I am trying to implement some custom elements with drag and drop functionality, using jQueryUI (although other libraries work similarly).  To add the functionality, the constructor functions require an already-rendered element.  [Edit: Actually I'm not sure they need to be rendered, but they certainly need to exist]

At the moment, I'm using jQuery's [`.ready()`](https://api.jquery.com/ready/) functionality to call the constructor function after the DOM is ready.  I've tried two methods:

1. Include a `div` in the template with some ID, then use `$()` to apply the functionality to the `div`
2. Construct a `div` using `document.createElement()`, apply the functionality to the element, then use `$()` to append it somewhere in the component

Both of these are using jQuery to wait for the component's elements to be created.  Is there a built-in way to do that?  Or are there some other preferred methods for handling this?

Any help appreciated...

**Comment by smalluban** [comment]
No worries, I am here to help, and it is actually a question from my todo list with more complicated topics, that should be explained.

As you already know (from #77) you should treat your properties in an independent way. As your request is to manipulate the DOM let's focus on the `render` factory. The docs examples show, that you are not forced to use built-in template engine, or any other library (like `lit-html`). 

If our body of the component is only produced by the third-party library, you can pass your own render function:

```javascript
function jqueryUI(settings) {
  return (host, target) => {
    // clear target content from the previous render
   target.innerHTML = '';
  
   // setup jQuery
   const div = document.createElement('div');
   target.appendChild(div);
   initializeJQueryUI(div, someValue);
  }
}

const MyElement = {
  someValue: 0,
  render: ({ someValue }) => jqueryUI({ someValue }),
};
```

The `target` will be `shadowRoot` or `host` according to your `render` factory setup. Take into account that update function (returned by `jqueryUI`) will be called each time when `someValue` changes (but with all goodies of RAF scheduling and dependency checks). Because of that, you need to control the situation when you already setup your element with an external tool. Maybe in your case, you can update settings without creating it from scratch. If you need to save reference to some variable according to host, the best way is to use `WeakMap`, and use `map.set(target, yourVariable) / map.get(target)`.

The second option is to use a built-in template engine and it's nested template feature (the `lit-html` requires `TemplateResult` object).

If you pass function reference, it will be called only once, as the reference will not change in sequential calls (in this case changing input props will not call your function again):

```javascript
import { html } from 'hybrids';

function jqueryUIOnce(host, target) {
  // setup jQuery
  const div = document.createElement('div');
   
   // In this case `target` is a TextNode placeholder - so we can use parent element - div#container
   // We have access to the `host`, so we can use `someValue` to initialize jquery
   initializeJQueryUI(target.parentElement, host.someValue);
}

const MyElement = {
  someValue: 0,
  render: ({ someValue }) => html`
    <div id="container">${jqueryUIOnce}</div>
    <div>other elements..., data: ${someValue}</div<>
  `,
};
```

Be aware that `jqueryUI` reference doesn't change, so if you change `someValue` - the function won't be called again.

However, if you want to have control with other inputs, you can use a similar way to the first example: 

```javascript
const MyElement = {
  someValue: 0,
  render: ({ someValue }) => html`
    <div id="container">${jqueryUI({ someValue })}</div>
    <div>other elements..., data: ${someValue}</div<>
  `,
};
```

The only difference is with `target` passed to the function - in this case, it is a TextNode - so then use `target.parentElement` to attach jQuery code to `div#container`.

**Comment by darrickyee** [comment]
Thanks.  I haven't implemented your idea exactly, but I attempted to do something similar using a custom lit-html directive.  It looks similar to your code in that it enables something like `${insertWidget('slider', options)}` in the template that will insert a slider widget at render time if it doesn't already exist.

The data binding is a little unpleasant, though.  Right now the `insertWidget` callback is listening for jQuery events on the widget and setting properties on the host.  For example, there's a 'slide' event whenever the slider handle is moved, so I'm updating the host component's 'value' when it changes.  Unfortunately, these are jQuery events that aren't visible to `addEventListener()`, but maybe I can rejigger things to fire custom events that could then be listened for using the usual tag attributes.

I wasn't familiar with `WeakMap` but I'm thinking it might help with binding the other way (from host to widget).  I guess the idea is to use a `WeakMap` as a sort of registry of objects for each host, like for example to hold a reference to the widget?

**Comment by smalluban** [comment]
I think in `lit-html` directive takes as an argument data, which is held during the lifecycle of the template - so you can save your jquery thing there. Using `WeakMap` could be helpful if you use built-in template, their nested template function takes the same two arguments as the main template - host and target, so sometimes you may need a place to store some information, and then `WeakMap` is one of the best choices, because even though might be a global variable does not create memory leak problem. You eed reference to your key to access value.
