### ISSUE TITLE
Strange text node of type {{h-timestamp-0}} on IE11 and Edge

### ISSUE THREAD

**Issue by ZaDarkSide** [hybridsjs/hybrids#79]
I've found a bug when rendering some components, I have made a JSFiddle to reproduce it.
A strange text node of type `{{h-timestamp-0}}` appears in the window titlebar near `BUG?=>`
It happens when you attach a css style with `style()` and I have reproduce it on IE11 and Edge.

Screenshot: [https://i.ibb.co/3S44Dk4/bug.png](https://i.ibb.co/3S44Dk4/bug.png)
JSFiddle: https://jsfiddle.net/ZaDarkSide/079kL2uq/16/

**Comment by smalluban** [comment]
I was able to reproduce a bug with minimal code. It is related to `<slot>` elements with a nested default structure. It's definitely caused by how ShadyDOM takes out those elements when template is prepared.

For now, there is a quick fix - if you put white spaces inside of your template the bug disappears, like this (https://codesandbox.io/s/cocky-bhaskara-qmx2p):

```
import '@webcomponents/webcomponentsjs/webcomponents-bundle.js';
import { html, define } from 'hybrids';

define('slot-with-bug', {
  render: () => html`<slot><span>Default</span></slot>`.style(''),
});

define('slot-without-bug', {
  render: () => html`
    <slot>
      <span>Default</span>
    </slot>
  `.style(''),
});
```

I the meantime I will try to find a fix for that.

**Comment by ZaDarkSide** [comment]
Any update on this?

**Comment by smalluban** [comment]
Unfortunately, I didn't have time to look closer at the problem. Did you try to make a quick fix with adding white space inside the slot element? 

I'll try to find some time next week. I will update you on the progress.

**Comment by smalluban** [comment]
@ZaDarkSide `v4.0.4` has been released with a fix ;)
