### ISSUE TITLE
Parsing Boolean Attribute Values

### ISSUE THREAD

**Issue by auzmartist** [hybridsjs/hybrids#92]
Greetings Dominik, 
I've been tinkering around with hybrids and I love the simplicity! However, I have come across a rather annoying problem when assigning boolean properties by attribute. I've created a minimal example here:

https://stackblitz.com/edit/hybrids-simple-boolean

Essentially, because the `Boolean` constructor is used as the boolean transform type, a boolean property with its default set to `true` will be locked as `true`:

```javascript
define('simple-boolean', {
    // https://hybrids.js.org/built-in-factories/property#transform-types
    value: property(true),
    render: ({value}) => html`${value}`,
})
```

```html
<simple-boolean value="false"></simple-boolean>
```

My initial reaction was to propose changing the transform type for boolean properties to a `JSON.parse()` function. This would handle `true`, `'true'`, `false`, and `'false'` well but would not handle numbers such as 0 and 1 as elegantly as the Boolean constructor does.

Here's a hybrid approach. Perhaps you have some opinion on performance as well...

```javascript
function transformBoolean(value) {
  value = value.toLowerCase()
  if (value === 'true' || value === 'false') {
    return JSON.parse(value)
  } else {
    return Boolean(value)
  }
}
```

**Comment by smalluban** [comment]
Hi @auzmartist! It's a little bit more complicated... because of how HTML works. Hybrids property factory, as well as the template engine (about setting attributes & properties), follow HTML documentation. How it works is not bad or good, it just works like that. I will try to explain it to you.

This is a part of the [HTML documentation](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes):

> A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.
>
> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.
>
> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

The attributes can hold only string values - simple fact. The idea of boolean attributes must have been invented after. They just not fit well in that convention. So what was done to support them? The standard says that if an attribute is **defined** (no matter with what value) it's boolean value is always "true". You can check it out by using one of the built-in attributes, like "hidden". If you try to set `hidden="false"`, its value still equals `true`. You have two ways to set those attributes to false: not define the attribute, or set it value to an empty string. The "true" and "false" string values are not supported.

However, I checked your example, and passing an empty string does not work as it should, and I know why.  I really appreciate your work for preparing  #93, but I can't merge your changes - they are not consistent with the HTML standard.

The problem is urgent because for all types of the values it works wrong when passing empty string (because then the factory passes `true` as a value). I will try to fix this as soon as possible and let you know.

**Comment by auzmartist** [comment]
Ah I understand. Thanks for being a good steward of the spec. It makes this library better 👍 

In my specific use case, I am trying to proxy properties of threeJS objects onto Hybrids components. So for example:

```html
<gl-mesh name="mesh.001" visible>...</gl-mesh>
```
This represents (with vanilla three JS):
```javascript
const mesh = new THREE.Mesh(defaultGeometry, defaultMaterial)
mesh.name = 'mesh.001'
mesh.visible = true // this is the default
```

By default (in the actual threeJS object, the value of `visible` is defaulted to true. So naturally, I wanted to set the property default to `true`. 

I think that there are a few workarounds here. If the default is true, then the opposite value could be exposed as an attribute:

```html
<gl-mesh name="mesh.001" invisible></gl-mesh>
```

This seems most clean. Otherwise, I could imagine exposing a string property and then coercing to a boolean in the various descriptor functions. I already do some data transformation in get/set like this to handle positions and euler rotations...

**Comment by smalluban** [comment]
As defaults are chosen for the most likely case, creating an `invisible` attribute might be the best choice. users of that component usually will not have to write anything (like the `hidden` attribute for DOM elements is used rarely).

**Comment by smalluban** [comment]
The booleans worked as expected, but because of your issue, I found that other types don't work properly for empty string in the attribute. I made a fix for that today - https://github.com/hybridsjs/hybrids/commit/49a9eb1947af98cd9213c96b06118149aac92391, so thanks for creating the issue!
